config/routes.rb
Pfe2::Application.routes.draw do
  resources :foods

  resources :clothings

  resources :items

  resources :orders

  resources :selections

  resources :visits

  get "welcome/index"
  resources :stores

  resources :owners

  resources :users

  resources :clients

  resources :payment_data

  resources :social_data

  resources :preferences

  resources :installation_data

  resources :parse_data

  root 'welcome#index'

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :User
  has_one :Payment_datum
  has_one :Social_datum
  has_many :Preference
  has_one :Installation_datum
  has_one :Visit
end

app/models/clothing.rb
class Clothing < ActiveRecord::Base
  belongs_to :Item
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :Item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :Selection
  has_many :Food
  has_many :Clothing
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :Selection
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :User
  has_many :Store
end

app/models/parse_datum.rb
class ParseDatum < ActiveRecord::Base
  belongs_to :User
end

app/models/payment_datum.rb
class PaymentDatum < ActiveRecord::Base
  belongs_to :Client
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :Client
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :Visit
  has_many :Order
  has_many :Item
end

app/models/social_datum.rb
class SocialDatum < ActiveRecord::Base
  belongs_to :Client
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :Owner
  has_many :Visit
  self.inheritance_column = nil
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :Client
  has_many :Owner
  has_one :Parse_datum
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :Client
  belongs_to :Store
  has_many :Selection
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
    @users = User.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @owner }
      else
        format.html { render action: 'new' }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:User_id, :facebookappid, :description, :facebookappkey)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :User_id%><br>
    <%= f.text_field :User_id%>
  </div>
  <div class="field">
    <%= f.label :facebookappid %><br>
    <%= f.text_field :facebookappid %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :facebookappkey %><br>
    <%= f.text_field :facebookappkey %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Facebookappid</th>
      <th>Description</th>
      <th>Facebookappkey</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= User.find(owner.User_id).name %></td>
        <td><%= owner.facebookappid %></td>
        <td><%= owner.description %></td>
        <td><%= owner.facebookappkey %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @owner.User %>
</p>

<p>
  <strong>Facebookappid:</strong>
  <%= @owner.facebookappid %>
</p>

<p>
  <strong>Description:</strong>
  <%= @owner.description %>
</p>

<p>
  <strong>Facebookappkey:</strong>
  <%= @owner.facebookappkey %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>