config/routes.rb
Pfe2::Application.routes.draw do
  resources :foods

  resources :clothings

  resources :items

  resources :orders

  resources :selections

  resources :visits

  get "welcome/index"
  resources :stores

  resources :owners

  resources :users

  resources :clients

  resources :payment_data

  resources :social_data

  resources :preferences

  resources :installation_data

  resources :parse_data

  root 'welcome#index'

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :User
  has_one :Payment_datum
  has_one :Social_datum
  has_many :Preference
  has_one :Installation_datum
  has_one :Visit
end

app/models/clothing.rb
class Clothing < ActiveRecord::Base
  belongs_to :Item
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :Item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :Selection
  has_many :Food
  has_many :Clothing
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :Selection
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :User
  has_many :Store
end

app/models/parse_datum.rb
class ParseDatum < ActiveRecord::Base
  belongs_to :User
end

app/models/payment_datum.rb
class PaymentDatum < ActiveRecord::Base
  belongs_to :Client
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :Client
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :Visit
  has_many :Order
  has_many :Item
end

app/models/social_datum.rb
class SocialDatum < ActiveRecord::Base
  belongs_to :Client
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :Owner
  has_many :Visit
  self.inheritance_column = nil
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :Client
  has_many :Owner
  has_one :Parse_datum
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :Client
  belongs_to :Store
  has_many :Selection
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
    @clients = Client.all
    @stores = Store.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @visit }
      else
        format.html { render action: 'new' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:Client_id, :timeinstore)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Client_id %><br>
    <%= f.text_field :Client_id %>
  </div>
  <div class="field">
    <%= f.label :timeinstore %><br>
    <%= f.number_field :timeinstore %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Timeinstore</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= User.find(Client.find(visit.Client_id).User_id).name %></td>
        <td><%= visit.timeinstore %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @visit.Client %>
</p>

<p>
  <strong>Timeinstore:</strong>
  <%= @visit.timeinstore %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>