config/routes.rb
Pfe2::Application.routes.draw do
  resources :foods

  resources :clothings

  resources :items

  resources :orders

  resources :selections

  resources :visits

  get "welcome/index"
  resources :stores

  resources :owners

  resources :users

  resources :clients

  resources :payment_data

  resources :social_data

  resources :preferences

  resources :installation_data

  resources :parse_data

  root 'welcome#index'

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :User
  has_one :Payment_datum
  has_one :Social_datum
  has_many :Preference
  has_one :Installation_datum
  has_one :Visit
end

app/models/clothing.rb
class Clothing < ActiveRecord::Base
  belongs_to :Item
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :Item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :Selection
  has_many :Food
  has_many :Clothing
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :Selection
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :User
  has_many :Store
end

app/models/parse_datum.rb
class ParseDatum < ActiveRecord::Base
  belongs_to :User
end

app/models/payment_datum.rb
class PaymentDatum < ActiveRecord::Base
  belongs_to :Client
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :Client
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :Visit
  has_many :Order
  has_many :Item
end

app/models/social_datum.rb
class SocialDatum < ActiveRecord::Base
  belongs_to :Client
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :Owner
  has_many :Visit
  self.inheritance_column = nil
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :Client
  has_many :Owner
  has_one :Parse_datum
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :Client
  belongs_to :Store
  has_many :Selection
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
    @owners = Owner.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:Owner_id, :name, :address, :city, :country, :numberfittingroom, :type)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Owner_id %><br>
    <%= f.text_field :Owner_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :numberfittingroom %><br>
    <%= f.number_field :numberfittingroom %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Country</th>
      <th>Numberfittingroom</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= User.find(Owner.find(store.Owner_id).User_id).name %></td>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= store.city %></td>
        <td><%= store.country %></td>
        <td><%= store.numberfittingroom %></td>
        <td><%= store.type %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @store.Owner %>
</p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @store.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @store.country %>
</p>

<p>
  <strong>Numberfittingroom:</strong>
  <%= @store.numberfittingroom %>
</p>

<p>
  <strong>Type:</strong>
  <%= @store.type %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>