config/routes.rb
Pfe2::Application.routes.draw do
  resources :foods

  resources :clothings

  resources :items

  resources :orders

  resources :selections

  resources :visits

  get "welcome/index"
  resources :stores

  resources :owners

  resources :users

  resources :clients

  resources :payment_data

  resources :social_data

  resources :preferences

  resources :installation_data

  resources :parse_data

  root 'welcome#index'

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :User
  has_one :Payment_datum
  has_one :Social_datum
  has_many :Preference
  has_one :Installation_datum
  has_one :Visit
end

app/models/clothing.rb
class Clothing < ActiveRecord::Base
  belongs_to :Item
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :Item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :Selection
  has_many :Food
  has_many :Clothing
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :Selection
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :User
  has_many :Store
end

app/models/parse_datum.rb
class ParseDatum < ActiveRecord::Base
  belongs_to :User
end

app/models/payment_datum.rb
class PaymentDatum < ActiveRecord::Base
  belongs_to :Client
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :Client
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :Visit
  has_many :Order
  has_many :Item
end

app/models/social_datum.rb
class SocialDatum < ActiveRecord::Base
  belongs_to :Client
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :Owner
  has_many :Visit
  self.inheritance_column = nil
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :Client
  has_many :Owner
  has_one :Parse_datum
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :Client
  belongs_to :Store
  has_many :Selection
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all
    @clients = Client.all
    
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
  end

  # GET /preferences/new
  def new
    @preference = Preference.new
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(preference_params)

    respond_to do |format|
      if @preference.save
        format.html { redirect_to @preference, notice: 'Preference was successfully created.' }
        format.json { render action: 'show', status: :created, location: @preference }
      else
        format.html { render action: 'new' }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferences/1
  # PATCH/PUT /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        format.html { redirect_to @preference, notice: 'Preference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference.destroy
    respond_to do |format|
      format.html { redirect_to preferences_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:Client_id, :color, :brand, :theme)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/preferences/_form.html.erb
<%= form_for(@preference) do |f| %>
  <% if @preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% @preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Client_id %><br>
    <%= f.text_field :Client_id %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<h1>Editing preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @preference %> |
<%= link_to 'Back', preferences_path %>

app/views/preferences/index.html.erb
<h1>Listing preferences</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Color</th>
      <th>Brand</th>
      <th>Theme</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @preferences.each do |preference| %>
      <tr>
        <td><%= User.find(Client.find(preference.Client_id).User_id).name %></td>
        <td><%= preference.color %></td>
        <td><%= preference.brand %></td>
        <td><%= preference.theme %></td>
        <td><%= link_to 'Show', preference %></td>
        <td><%= link_to 'Edit', edit_preference_path(preference) %></td>
        <td><%= link_to 'Destroy', preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preference', new_preference_path %>

app/views/preferences/new.html.erb
<h1>New preference</h1>

<%= render 'form' %>

<%= link_to 'Back', preferences_path %>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @preference.Client %>
</p>

<p>
  <strong>Color:</strong>
  <%= @preference.color %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @preference.brand %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @preference.theme %>
</p>

<%= link_to 'Edit', edit_preference_path(@preference) %> |
<%= link_to 'Back', preferences_path %>